services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./media:/app/media  
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://admin:a@db:5432/db_face_scan

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: a
      POSTGRES_DB: db_face_scan

  training_service:
    build:
      context: ./training_service
      dockerfile: Dockerfile
    volumes:
      - ./media:/training_service/media
      - ./training_service:/training_service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgres://admin:a@db:5432/db_face_scan
    depends_on:
      - db

volumes:
  db_data: