services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./media:/media
      - .:/app  
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://admin:a@db:5432/db_face_scan
    networks:
      - face_network

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: a
      POSTGRES_DB: db_face_scan
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
    networks:
      - face_network

  training_service:
    build:
      context: ./training_service
      dockerfile: Dockerfile
    volumes:
      - ./media:/media
      - ./training_service:/training_service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgres://admin:a@db:5432/db_face_scan
    depends_on:
      - db
      - app
    networks:
      - face_network

volumes:
  db_data:

networks:
  face_network:
    driver: bridge
