services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./media:/app/media  
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://admin:a@db:5432/db_face_scan

  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: a
      POSTGRES_DB: db_face_scan

volumes:
  db_data:
