# Generated by Django 5.1.1 on 2025-01-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0003_device_room_facemodel_course_facemodel_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facemodel",
            name="inverse_label_map",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="facescanlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "Present"),
                    ("absent", "Absent"),
                    ("leave", "Leave"),
                ],
                max_length=10,
            ),
        ),
    ]
