# Generated by Django 5.1.1 on 2025-02-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0004_facemodel_inverse_label_map_alter_facescanlog_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facemodel",
            name="inverse_label_map",
        ),
        migrations.AddField(
            model_name="facemodel",
            name="embedding_size",
            field=models.IntegerField(default=128),
        ),
        migrations.AddField(
            model_name="facemodel",
            name="similarity_threshold",
            field=models.FloatField(default=0.7),
        ),
    ]
