# Generated by Django 5.1.1 on 2025-02-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0005_remove_facemodel_inverse_label_map_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facemodel",
            name="embedding_size",
        ),
        migrations.RemoveField(
            model_name="facemodel",
            name="similarity_threshold",
        ),
        migrations.AddField(
            model_name="facemodel",
            name="inverse_label_map",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
