# Generated by Django 5.1.1 on 2025-02-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0006_remove_facemodel_embedding_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facemodel",
            name="last_enrollment_count",
            field=models.IntegerField(default=0),
        ),
    ]
