# Generated by Django 5.1.1 on 2025-02-25 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0001_initial"),
    ]

    operations = []
