# Generated by Django 5.1.1 on 2025-01-21 12:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course_create_at_course_details_course_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="create_at",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
