# Generated by Django 5.1.1 on 2025-01-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_enrollment_create_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(
                blank=True,
                default="course_images/default.jpg",
                null=True,
                upload_to="course_images/",
            ),
        ),
    ]
