# Generated by Django 5.1.1 on 2025-02-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("teacher", "Teacher"),
                    ("admin", "Admin"),
                ],
                default="student",
                max_length=10,
            ),
        ),
    ]
