# Generated by Django 5.1.1 on 2025-01-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_alter_member_options_alter_member_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="profile_path",
            field=models.ImageField(
                blank=True,
                default="profile_images/default.jpg",
                null=True,
                upload_to="profile_images/",
            ),
        ),
    ]
