# Generated by Django 5.1.1 on 2025-01-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_alter_member_profile_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
