# Generated by Django 5.1.1 on 2025-01-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_alter_student_student_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="student_id",
            field=models.CharField(default=None, max_length=15, unique=True),
        ),
        migrations.DeleteModel(
            name="Student",
        ),
    ]
