# Generated by Django 5.1.1 on 2025-01-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_member_student_id_delete_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="student_id",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
