# Generated by Django 5.1.1 on 2025-02-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0006_alter_member_student_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
