# Generated by Django 5.1.1 on 2025-01-19 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_alter_attendance_schedule"),
        ("common", "0001_initial"),
        ("courses", "0001_initial"),
        ("devices", "0002_alter_trainingimage_file_path"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="device",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recorded_attendances",
                to="devices.device",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="common.room",
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["date", "schedule"], name="attendance__date_1cb817_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["student", "course"], name="attendance__student_e4c8ff_idx"
            ),
        ),
    ]
